//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fiction.GameScreen.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Fiction.GameScreen.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following magic items will be imported into this campaign.  Click Finish to complete the import..
        /// </summary>
        public static string AboutToImportMagicItemsLabel {
            get {
                return ResourceManager.GetString("AboutToImportMagicItemsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following monsters will be imported into this campaign.  Click Finish to complete the import..
        /// </summary>
        public static string AboutToImportMonstersLabel {
            get {
                return ResourceManager.GetString("AboutToImportMonstersLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following spells will be imported into the campaign.  Click Finish to complete the import..
        /// </summary>
        public static string AboutToImportSpellsLabel {
            get {
                return ResourceManager.GetString("AboutToImportSpellsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active Combat.
        /// </summary>
        public static string ActiveCombatMenuHeader {
            get {
                return ResourceManager.GetString("ActiveCombatMenuHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actual Amount.
        /// </summary>
        public static string ActualAmountLabel {
            get {
                return ResourceManager.GetString("ActualAmountLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Attribute....
        /// </summary>
        public static string AddAttributeHeader {
            get {
                return ResourceManager.GetString("AddAttributeHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string AddButton {
            get {
                return ResourceManager.GetString("AddButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string AddButtonToolTip {
            get {
                return ResourceManager.GetString("AddButtonToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Condition.
        /// </summary>
        public static string AddConditionMenuHeader {
            get {
                return ResourceManager.GetString("AddConditionMenuHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add to Combat.
        /// </summary>
        public static string AddToCombatDisplayName {
            get {
                return ResourceManager.GetString("AddToCombatDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add To Combat.
        /// </summary>
        public static string AddToCombatMenuHeader {
            get {
                return ResourceManager.GetString("AddToCombatMenuHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alignment.
        /// </summary>
        public static string AlignmentLabel {
            get {
                return ResourceManager.GetString("AlignmentLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow Overheal.
        /// </summary>
        public static string AllowOverHealLabel {
            get {
                return ResourceManager.GetString("AllowOverHealLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount.
        /// </summary>
        public static string AmountLabel {
            get {
                return ResourceManager.GetString("AmountLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply Damage Reduction.
        /// </summary>
        public static string ApplyDamageReduction {
            get {
                return ResourceManager.GetString("ApplyDamageReduction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply To Total.
        /// </summary>
        public static string ApplyToTotalLabel {
            get {
                return ResourceManager.GetString("ApplyToTotalLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Area.
        /// </summary>
        public static string AreaLabel {
            get {
                return ResourceManager.GetString("AreaLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Armor Class.
        /// </summary>
        public static string ArmorClassLabel {
            get {
                return ResourceManager.GetString("ArmorClassLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Artifact Level.
        /// </summary>
        public static string ArtifactLevelLabel {
            get {
                return ResourceManager.GetString("ArtifactLevelLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Major Artifact.
        /// </summary>
        public static string ArtifactLevelMajorLabel {
            get {
                return ResourceManager.GetString("ArtifactLevelMajorLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minor Artifact.
        /// </summary>
        public static string ArtifactLevelMinorLabel {
            get {
                return ResourceManager.GetString("ArtifactLevelMinorLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not an Artifact.
        /// </summary>
        public static string ArtifactLevelNoneLabel {
            get {
                return ResourceManager.GetString("ArtifactLevelNoneLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attribute:  {0}.
        /// </summary>
        public static string AttributeDefinitionViewModelDisplayName {
            get {
                return ResourceManager.GetString("AttributeDefinitionViewModelDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attribute Details.
        /// </summary>
        public static string AttributeDetailsHeader {
            get {
                return ResourceManager.GetString("AttributeDetailsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attributes.
        /// </summary>
        public static string AttributeListHeader {
            get {
                return ResourceManager.GetString("AttributeListHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attribute Modifiers.
        /// </summary>
        public static string AttributeModifierCategory {
            get {
                return ResourceManager.GetString("AttributeModifierCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From Attribute.
        /// </summary>
        public static string AttributeModifierFromAttributeDisplayName {
            get {
                return ResourceManager.GetString("AttributeModifierFromAttributeDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source:.
        /// </summary>
        public static string AttributeModifierSourceLabel {
            get {
                return ResourceManager.GetString("AttributeModifierSourceLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Static Modifier.
        /// </summary>
        public static string AttributeModifierStaticViewModelName {
            get {
                return ResourceManager.GetString("AttributeModifierStaticViewModelName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Campaign Attribute Modifiers.
        /// </summary>
        public static string AttributeModifiersViewModelName {
            get {
                return ResourceManager.GetString("AttributeModifiersViewModelName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Targets:.
        /// </summary>
        public static string AttributeModifierTargetsLabel {
            get {
                return ResourceManager.GetString("AttributeModifierTargetsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ability Score.
        /// </summary>
        public static string AttributeModifierType_AbilityScore {
            get {
                return ResourceManager.GetString("AttributeModifierType_AbilityScore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attribute Value.
        /// </summary>
        public static string AttributeModifierType_Value {
            get {
                return ResourceManager.GetString("AttributeModifierType_Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auras.
        /// </summary>
        public static string AurasLabel {
            get {
                return ResourceManager.GetString("AurasLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aura Strength.
        /// </summary>
        public static string AuraStrengthLabel {
            get {
                return ResourceManager.GetString("AuraStrengthLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Base Attack Bonus.
        /// </summary>
        public static string BaseAttackBonusLabel {
            get {
                return ResourceManager.GetString("BaseAttackBonusLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Begin.
        /// </summary>
        public static string BeginCombatButton {
            get {
                return ResourceManager.GetString("BeginCombatButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Begin Combat.
        /// </summary>
        public static string BeginCombatDisplayName {
            get {
                return ResourceManager.GetString("BeginCombatDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Begin Combat.
        /// </summary>
        public static string BeginCombatMenuHeader {
            get {
                return ResourceManager.GetString("BeginCombatMenuHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bestiary.
        /// </summary>
        public static string BestiaryMenuHeader {
            get {
                return ResourceManager.GetString("BestiaryMenuHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bypass Damage Reduction.
        /// </summary>
        public static string BypassDamageReduction {
            get {
                return ResourceManager.GetString("BypassDamageReduction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Attributes.
        /// </summary>
        public static string CampaignAttributesMenuHeader {
            get {
                return ResourceManager.GetString("CampaignAttributesMenuHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attributes.
        /// </summary>
        public static string CampaignAttributesViewModelName {
            get {
                return ResourceManager.GetString("CampaignAttributesViewModelName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Campaign.
        /// </summary>
        public static string CampaignMenuHeader {
            get {
                return ResourceManager.GetString("CampaignMenuHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attribute Modifiers.
        /// </summary>
        public static string CampaignModifiersMenuHeader {
            get {
                return ResourceManager.GetString("CampaignModifiersMenuHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Races.
        /// </summary>
        public static string CampaignRacesViewModelDisplayName {
            get {
                return ResourceManager.GetString("CampaignRacesViewModelDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Campaign Settings.
        /// </summary>
        public static string CampaignSettingsCategory {
            get {
                return ResourceManager.GetString("CampaignSettingsCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Special Qualities.
        /// </summary>
        public static string CampaignSpecialQualitiesDisplayName {
            get {
                return ResourceManager.GetString("CampaignSpecialQualitiesDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string CancelWizardButton {
            get {
                return ResourceManager.GetString("CancelWizardButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot delete this combatant because it is currently in use..
        /// </summary>
        public static string CannotDeleteCombatantMessage {
            get {
                return ResourceManager.GetString("CannotDeleteCombatantMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot delete this combat scenario because it is currently in use, or one of its combatants is currently in use..
        /// </summary>
        public static string CannotDeleteCombatScenarioMessage {
            get {
                return ResourceManager.GetString("CannotDeleteCombatScenarioMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Caster Level.
        /// </summary>
        public static string CasterLevelLabel {
            get {
                return ResourceManager.GetString("CasterLevelLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Casting Time.
        /// </summary>
        public static string CastingTimeLabel {
            get {
                return ResourceManager.GetString("CastingTimeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        public static string CategoryLabel {
            get {
                return ResourceManager.GetString("CategoryLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Challenge Rating.
        /// </summary>
        public static string ChallengeRatingLabel {
            get {
                return ResourceManager.GetString("ChallengeRatingLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chaotic Evil.
        /// </summary>
        public static string ChaoticEvilAlignment {
            get {
                return ResourceManager.GetString("ChaoticEvilAlignment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chaotic Good.
        /// </summary>
        public static string ChaoticGoodAlignment {
            get {
                return ResourceManager.GetString("ChaoticGoodAlignment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chaotic Neutral.
        /// </summary>
        public static string ChaoticNeutralAlignment {
            get {
                return ResourceManager.GetString("ChaoticNeutralAlignment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Charisma.
        /// </summary>
        public static string CharismaLabel {
            get {
                return ResourceManager.GetString("CharismaLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose a Source.
        /// </summary>
        public static string ChooseSourceLabel {
            get {
                return ResourceManager.GetString("ChooseSourceLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class.
        /// </summary>
        public static string ClassLabel {
            get {
                return ResourceManager.GetString("ClassLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string CloseButton {
            get {
                return ResourceManager.GetString("CloseButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collosal.
        /// </summary>
        public static string CollosalSize {
            get {
                return ResourceManager.GetString("CollosalSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Combatants.
        /// </summary>
        public static string CombatantsLabel {
            get {
                return ResourceManager.GetString("CombatantsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Combat.
        /// </summary>
        public static string CombatCategory {
            get {
                return ResourceManager.GetString("CombatCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CMB.
        /// </summary>
        public static string CombatManeuverBonusLabel {
            get {
                return ResourceManager.GetString("CombatManeuverBonusLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CMD.
        /// </summary>
        public static string CombatManeuverDefenseLabel {
            get {
                return ResourceManager.GetString("CombatManeuverDefenseLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Combat.
        /// </summary>
        public static string CombatMenuHeader {
            get {
                return ResourceManager.GetString("CombatMenuHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Combat Scenarios.
        /// </summary>
        public static string CombatScenariosViewModelDisplayName {
            get {
                return ResourceManager.GetString("CombatScenariosViewModelDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Communications.
        /// </summary>
        public static string CommunicationLabel {
            get {
                return ResourceManager.GetString("CommunicationLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Components.
        /// </summary>
        public static string ComponentsLabel {
            get {
                return ResourceManager.GetString("ComponentsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conditions.
        /// </summary>
        public static string ConditionsMenuHeader {
            get {
                return ResourceManager.GetString("ConditionsMenuHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conditions.
        /// </summary>
        public static string ConditionsViewModelName {
            get {
                return ResourceManager.GetString("ConditionsViewModelName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect To Server.
        /// </summary>
        public static string ConnectToServerMenuHeader {
            get {
                return ResourceManager.GetString("ConnectToServerMenuHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Constitution.
        /// </summary>
        public static string ConstitutionLabel {
            get {
                return ResourceManager.GetString("ConstitutionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string CopyButton {
            get {
                return ResourceManager.GetString("CopyButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Copy.
        /// </summary>
        public static string CopyButtonToolTip {
            get {
                return ResourceManager.GetString("CopyButtonToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cost.
        /// </summary>
        public static string CostLabel {
            get {
                return ResourceManager.GetString("CostLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Costly Components.
        /// </summary>
        public static string CostlyComponentsLabel {
            get {
                return ResourceManager.GetString("CostlyComponentsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Count.
        /// </summary>
        public static string CountLabel {
            get {
                return ResourceManager.GetString("CountLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ▶.
        /// </summary>
        public static string CurrentCombatantMarker {
            get {
                return ResourceManager.GetString("CurrentCombatantMarker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Round.
        /// </summary>
        public static string CurrentRoundLabel {
            get {
                return ResourceManager.GetString("CurrentRoundLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to d20 GameScreen.
        /// </summary>
        public static string d20GameScreenLabel {
            get {
                return ResourceManager.GetString("d20GameScreenLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Damage.
        /// </summary>
        public static string DamageCombatantsButton {
            get {
                return ResourceManager.GetString("DamageCombatantsButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Damage.
        /// </summary>
        public static string DamageLabel {
            get {
                return ResourceManager.GetString("DamageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Damage Reduction.
        /// </summary>
        public static string DamageReductionLabel {
            get {
                return ResourceManager.GetString("DamageReductionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Damage Types.
        /// </summary>
        public static string DamageTypesLabel {
            get {
                return ResourceManager.GetString("DamageTypesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dead At.
        /// </summary>
        public static string DeadAtLabel {
            get {
                return ResourceManager.GetString("DeadAtLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Defense.
        /// </summary>
        public static string DefenseLabel {
            get {
                return ResourceManager.GetString("DefenseLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Defense.
        /// </summary>
        public static string DefenseLabel1 {
            get {
                return ResourceManager.GetString("DefenseLabel1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string DescriptionLabel {
            get {
                return ResourceManager.GetString("DescriptionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string DescriptionLabel1 {
            get {
                return ResourceManager.GetString("DescriptionLabel1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deselect All.
        /// </summary>
        public static string DeselectAllButton {
            get {
                return ResourceManager.GetString("DeselectAllButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destruction.
        /// </summary>
        public static string DestructionLabel {
            get {
                return ResourceManager.GetString("DestructionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        public static string DetailsHeader {
            get {
                return ResourceManager.GetString("DetailsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dexterity.
        /// </summary>
        public static string DexterityLabel {
            get {
                return ResourceManager.GetString("DexterityLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diminutive.
        /// </summary>
        public static string DiminutiveSize {
            get {
                return ResourceManager.GetString("DiminutiveSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dismissible.
        /// </summary>
        public static string DismissibleLabel {
            get {
                return ResourceManager.GetString("DismissibleLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display Name.
        /// </summary>
        public static string DisplayNameLabel {
            get {
                return ResourceManager.GetString("DisplayNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display To Players.
        /// </summary>
        public static string DisplayToPlayersLabel {
            get {
                return ResourceManager.GetString("DisplayToPlayersLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Overwrite.
        /// </summary>
        public static string DoNotOverwriteButton {
            get {
                return ResourceManager.GetString("DoNotOverwriteButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Double Damage (200%).
        /// </summary>
        public static string DoubleDamageLabel {
            get {
                return ResourceManager.GetString("DoubleDamageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duration.
        /// </summary>
        public static string DurationLabel {
            get {
                return ResourceManager.GetString("DurationLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Attribute....
        /// </summary>
        public static string EditAttributeHeader {
            get {
                return ResourceManager.GetString("EditAttributeHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string EditButton {
            get {
                return ResourceManager.GetString("EditButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string EditButtonToolTip {
            get {
                return ResourceManager.GetString("EditButtonToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Effect.
        /// </summary>
        public static string EditEffectMenuHeader {
            get {
                return ResourceManager.GetString("EditEffectMenuHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Effect.
        /// </summary>
        public static string EffectLabel {
            get {
                return ResourceManager.GetString("EffectLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Effects.
        /// </summary>
        public static string EffectsLabel {
            get {
                return ResourceManager.GetString("EffectsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Effect Types.
        /// </summary>
        public static string EffectTypesLabel {
            get {
                return ResourceManager.GetString("EffectTypesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ego.
        /// </summary>
        public static string EgoLabel {
            get {
                return ResourceManager.GetString("EgoLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ….
        /// </summary>
        public static string EllipsisButton {
            get {
                return ResourceManager.GetString("EllipsisButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encounter Members.
        /// </summary>
        public static string EncounterMembersLabel {
            get {
                return ResourceManager.GetString("EncounterMembersLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End.
        /// </summary>
        public static string EndButton {
            get {
                return ResourceManager.GetString("EndButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End the current combat?.
        /// </summary>
        public static string EndCombatWarningMessage {
            get {
                return ResourceManager.GetString("EndCombatWarningMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Environment.
        /// </summary>
        public static string EnvironmentLabel {
            get {
                return ResourceManager.GetString("EnvironmentLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Equipment.
        /// </summary>
        public static string EquipmentCategory {
            get {
                return ResourceManager.GetString("EquipmentCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Equipment.
        /// </summary>
        public static string EquipmentMenuHeader {
            get {
                return ResourceManager.GetString("EquipmentMenuHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following effects expired.
        /// </summary>
        public static string ExpiredEffectsInformationLabel {
            get {
                return ResourceManager.GetString("ExpiredEffectsInformationLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fast Healing.
        /// </summary>
        public static string FastHealingLabel {
            get {
                return ResourceManager.GetString("FastHealingLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feats.
        /// </summary>
        public static string FeatsLabel {
            get {
                return ResourceManager.GetString("FeatsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string FilterButton {
            get {
                return ResourceManager.GetString("FilterButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter.
        /// </summary>
        public static string FilterLabel {
            get {
                return ResourceManager.GetString("FilterLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fine.
        /// </summary>
        public static string FineSize {
            get {
                return ResourceManager.GetString("FineSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finish.
        /// </summary>
        public static string FinishWizardButton {
            get {
                return ResourceManager.GetString("FinishWizardButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flat-Footed Armor Class.
        /// </summary>
        public static string FlatFootedArmorClassLabel {
            get {
                return ResourceManager.GetString("FlatFootedArmorClassLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fortitude.
        /// </summary>
        public static string FortitudeLabel {
            get {
                return ResourceManager.GetString("FortitudeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gargantuan.
        /// </summary>
        public static string GargantuanSize {
            get {
                return ResourceManager.GetString("GargantuanSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        public static string GeneralLabel {
            get {
                return ResourceManager.GetString("GeneralLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group.
        /// </summary>
        public static string GroupLabel {
            get {
                return ResourceManager.GetString("GroupLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Half Again Damage (150%).
        /// </summary>
        public static string HalfAgainDamageLabel {
            get {
                return ResourceManager.GetString("HalfAgainDamageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Half Damage (50%).
        /// </summary>
        public static string HalfDamageLabel {
            get {
                return ResourceManager.GetString("HalfDamageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heal.
        /// </summary>
        public static string HealCombatantsButton {
            get {
                return ResourceManager.GetString("HealCombatantsButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hit Dice.
        /// </summary>
        public static string HitDiceLabel {
            get {
                return ResourceManager.GetString("HitDiceLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hit Points.
        /// </summary>
        public static string HitPointsLabel {
            get {
                return ResourceManager.GetString("HitPointsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Huge.
        /// </summary>
        public static string HugeSize {
            get {
                return ResourceManager.GetString("HugeSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Immunities.
        /// </summary>
        public static string ImmunitiesLabel {
            get {
                return ResourceManager.GetString("ImmunitiesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import.
        /// </summary>
        public static string ImportMenuHeader {
            get {
                return ResourceManager.GetString("ImportMenuHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include In Combat.
        /// </summary>
        public static string IncludeInCombatLabel {
            get {
                return ResourceManager.GetString("IncludeInCombatLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initiative Modifier.
        /// </summary>
        public static string InitiativeModifierLabel {
            get {
                return ResourceManager.GetString("InitiativeModifierLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initiative Order.
        /// </summary>
        public static string InitiativeOrderLabel {
            get {
                return ResourceManager.GetString("InitiativeOrderLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initiative Roll.
        /// </summary>
        public static string InitiativeRollLabel {
            get {
                return ResourceManager.GetString("InitiativeRollLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initiative Count Combatant.
        /// </summary>
        public static string InitiativeSourceLabel {
            get {
                return ResourceManager.GetString("InitiativeSourceLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Initiative.
        /// </summary>
        public static string InitiativeTotalLabel {
            get {
                return ResourceManager.GetString("InitiativeTotalLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intelligence.
        /// </summary>
        public static string IntelligenceLabel {
            get {
                return ResourceManager.GetString("IntelligenceLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intelligent.
        /// </summary>
        public static string IsIntelligentLabel {
            get {
                return ResourceManager.GetString("IsIntelligentLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lethal Damage.
        /// </summary>
        public static string IsLethalLabel {
            get {
                return ResourceManager.GetString("IsLethalLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Magical.
        /// </summary>
        public static string IsMagicalLabel {
            get {
                return ResourceManager.GetString("IsMagicalLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kill.
        /// </summary>
        public static string KillCombatantMenuHeader {
            get {
                return ResourceManager.GetString("KillCombatantMenuHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Languages.
        /// </summary>
        public static string LanguagesLabel {
            get {
                return ResourceManager.GetString("LanguagesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Languages.
        /// </summary>
        public static string LanguagesLabel1 {
            get {
                return ResourceManager.GetString("LanguagesLabel1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Large.
        /// </summary>
        public static string LargeSize {
            get {
                return ResourceManager.GetString("LargeSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lawful Evil.
        /// </summary>
        public static string LawfulEvilAlignment {
            get {
                return ResourceManager.GetString("LawfulEvilAlignment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lawful Good.
        /// </summary>
        public static string LawfulGoodAlignment {
            get {
                return ResourceManager.GetString("LawfulGoodAlignment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lawful Neutral.
        /// </summary>
        public static string LawfulNeutralAlignment {
            get {
                return ResourceManager.GetString("LawfulNeutralAlignment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level.
        /// </summary>
        public static string LevelLabel {
            get {
                return ResourceManager.GetString("LevelLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light Radius.
        /// </summary>
        public static string LightRadiusLabel {
            get {
                return ResourceManager.GetString("LightRadiusLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Magic Items.
        /// </summary>
        public static string MagicItemsDisplayName {
            get {
                return ResourceManager.GetString("MagicItemsDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Magic Items.
        /// </summary>
        public static string MagicItemsMenuHeader {
            get {
                return ResourceManager.GetString("MagicItemsMenuHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to d20 GameScreen Desktop.
        /// </summary>
        public static string MainWindowTitle {
            get {
                return ResourceManager.GetString("MainWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage.
        /// </summary>
        public static string ManageCombatantsButton {
            get {
                return ResourceManager.GetString("ManageCombatantsButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Monsters.
        /// </summary>
        public static string ManageMonstersDisplayName {
            get {
                return ResourceManager.GetString("ManageMonstersDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monster Types.
        /// </summary>
        public static string ManageMonsterTypesDisplayName {
            get {
                return ResourceManager.GetString("ManageMonsterTypesDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monster Types and SubTypes.
        /// </summary>
        public static string ManageMonsterTypesMenuHeader {
            get {
                return ResourceManager.GetString("ManageMonsterTypesMenuHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scenarios.
        /// </summary>
        public static string ManageScenariosMenuHeader {
            get {
                return ResourceManager.GetString("ManageScenariosMenuHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sources.
        /// </summary>
        public static string ManageSourcesDisplayName {
            get {
                return ResourceManager.GetString("ManageSourcesDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Sources.
        /// </summary>
        public static string ManageSourcesMenuItem {
            get {
                return ResourceManager.GetString("ManageSourcesMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schools and Effects.
        /// </summary>
        public static string ManageSpellSchoolsDisplayName {
            get {
                return ResourceManager.GetString("ManageSpellSchoolsDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Spell Schools and Effects.
        /// </summary>
        public static string ManageSpellSchoolsLabel {
            get {
                return ResourceManager.GetString("ManageSpellSchoolsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spells.
        /// </summary>
        public static string ManageSpellsDisplayName {
            get {
                return ResourceManager.GetString("ManageSpellsDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Spells.
        /// </summary>
        public static string ManageSpellsMenuHeader {
            get {
                return ResourceManager.GetString("ManageSpellsMenuHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum Hit Points.
        /// </summary>
        public static string MaxHitPointsLabel {
            get {
                return ResourceManager.GetString("MaxHitPointsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum Price.
        /// </summary>
        public static string MaximumPriceLabel {
            get {
                return ResourceManager.GetString("MaximumPriceLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medium.
        /// </summary>
        public static string MediumSize {
            get {
                return ResourceManager.GetString("MediumSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Melee Attacks.
        /// </summary>
        public static string MeleeLabel {
            get {
                return ResourceManager.GetString("MeleeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are about to merge every item from {0} to {1}.  Are you sure you want to do this?.
        /// </summary>
        public static string MergeSourceWarning {
            get {
                return ResourceManager.GetString("MergeSourceWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum Price.
        /// </summary>
        public static string MinimumPriceLabel {
            get {
                return ResourceManager.GetString("MinimumPriceLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attribute Modifiers.
        /// </summary>
        public static string ModifiersLabel {
            get {
                return ResourceManager.GetString("ModifiersLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default for Type.
        /// </summary>
        public static string ModifierStackingType_Default {
            get {
                return ResourceManager.GetString("ModifierStackingType_Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Stacking.
        /// </summary>
        public static string ModifierStackingType_NonStacking {
            get {
                return ResourceManager.GetString("ModifierStackingType_NonStacking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stacks.
        /// </summary>
        public static string ModifierStackingType_Stacking {
            get {
                return ResourceManager.GetString("ModifierStackingType_Stacking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modifier Types.
        /// </summary>
        public static string ModifierTypeCategory {
            get {
                return ResourceManager.GetString("ModifierTypeCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modifier Type.
        /// </summary>
        public static string ModifierTypeLabel {
            get {
                return ResourceManager.GetString("ModifierTypeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modifier Types.
        /// </summary>
        public static string ModifierTypesMenuHeader {
            get {
                return ResourceManager.GetString("ModifierTypesMenuHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modifier Types.
        /// </summary>
        public static string ModifierTypesViewModelName {
            get {
                return ResourceManager.GetString("ModifierTypesViewModelName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bestiary.
        /// </summary>
        public static string MonstersCategory {
            get {
                return ResourceManager.GetString("MonstersCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monsters.
        /// </summary>
        public static string MonstersMenuHeader {
            get {
                return ResourceManager.GetString("MonstersMenuHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monster Types.
        /// </summary>
        public static string MonsterTypesLabel {
            get {
                return ResourceManager.GetString("MonsterTypesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move to After Current (Delayed Action).
        /// </summary>
        public static string MoveAfterCurrentMenuHeader {
            get {
                return ResourceManager.GetString("MoveAfterCurrentMenuHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move to Before Current (Prepared Action).
        /// </summary>
        public static string MoveBeforeCurrentMenuHeader {
            get {
                return ResourceManager.GetString("MoveBeforeCurrentMenuHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mythic.
        /// </summary>
        public static string MythicLabel {
            get {
                return ResourceManager.GetString("MythicLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string NameLabel {
            get {
                return ResourceManager.GetString("NameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neutral Evil.
        /// </summary>
        public static string NeutralEvilAlignment {
            get {
                return ResourceManager.GetString("NeutralEvilAlignment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neutral Good.
        /// </summary>
        public static string NeutralGoodAlignment {
            get {
                return ResourceManager.GetString("NeutralGoodAlignment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to True Neutral.
        /// </summary>
        public static string NeutralNeutralAlignment {
            get {
                return ResourceManager.GetString("NeutralNeutralAlignment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Attribute.
        /// </summary>
        public static string NewAttributeDefinitionName {
            get {
                return ResourceManager.GetString("NewAttributeDefinitionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Type.
        /// </summary>
        public static string NewAttributeDefinitionType {
            get {
                return ResourceManager.GetString("NewAttributeDefinitionType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _New.
        /// </summary>
        public static string NewCampaignMenuHeader {
            get {
                return ResourceManager.GetString("NewCampaignMenuHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create effect from this combatant.
        /// </summary>
        public static string NewEffectMenuItem {
            get {
                return ResourceManager.GetString("NewEffectMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Modifier Type.
        /// </summary>
        public static string NewModifierTypeName {
            get {
                return ResourceManager.GetString("NewModifierTypeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        public static string NextCombatantButton {
            get {
                return ResourceManager.GetString("NextCombatantButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        public static string NextPageButton {
            get {
                return ResourceManager.GetString("NextPageButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Damage.
        /// </summary>
        public static string NoDamageLabel {
            get {
                return ResourceManager.GetString("NoDamageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        public static string NoneLabel {
            get {
                return ResourceManager.GetString("NoneLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non-lethal.
        /// </summary>
        public static string NonLethalDamageLabel {
            get {
                return ResourceManager.GetString("NonLethalDamageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ▶.
        /// </summary>
        public static string NoteMarker {
            get {
                return ResourceManager.GetString("NoteMarker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notes.
        /// </summary>
        public static string NotesLabel {
            get {
                return ResourceManager.GetString("NotesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} will be overwritten.
        /// </summary>
        public static string NumberWillBeOverwrittenLabel {
            get {
                return ResourceManager.GetString("NumberWillBeOverwrittenLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offense.
        /// </summary>
        public static string OffenseLabel {
            get {
                return ResourceManager.GetString("OffenseLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Campaign.
        /// </summary>
        public static string OpenCampaignDialogTitle {
            get {
                return ResourceManager.GetString("OpenCampaignDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Campaign.
        /// </summary>
        public static string OpenCampaignMenuHeader {
            get {
                return ResourceManager.GetString("OpenCampaignMenuHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organisation.
        /// </summary>
        public static string OrganisationLabel {
            get {
                return ResourceManager.GetString("OrganisationLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overwrite.
        /// </summary>
        public static string OverwriteButton {
            get {
                return ResourceManager.GetString("OverwriteButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overwrite.
        /// </summary>
        public static string OverwriteLabel {
            get {
                return ResourceManager.GetString("OverwriteLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to d20 PFSRD CSV file.
        /// </summary>
        public static string PfsrdImportLabel {
            get {
                return ResourceManager.GetString("PfsrdImportLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player.
        /// </summary>
        public static string PlayerNameLabel {
            get {
                return ResourceManager.GetString("PlayerNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Players.
        /// </summary>
        public static string PlayersDisplayName {
            get {
                return ResourceManager.GetString("PlayersDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Players.
        /// </summary>
        public static string PlayersMenuHeader {
            get {
                return ResourceManager.GetString("PlayersMenuHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Powers.
        /// </summary>
        public static string PowersLabel {
            get {
                return ResourceManager.GetString("PowersLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prep Info.
        /// </summary>
        public static string PrepareInfoLabel {
            get {
                return ResourceManager.GetString("PrepareInfoLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information used to create this combatant..
        /// </summary>
        public static string PrepareInfoToolTip {
            get {
                return ResourceManager.GetString("PrepareInfoToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous.
        /// </summary>
        public static string PrevPageButton {
            get {
                return ResourceManager.GetString("PrevPageButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price.
        /// </summary>
        public static string PriceLabel {
            get {
                return ResourceManager.GetString("PriceLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quarter Damage (25%).
        /// </summary>
        public static string QuarterDamageLabel {
            get {
                return ResourceManager.GetString("QuarterDamageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Races.
        /// </summary>
        public static string RacesMenuHeader {
            get {
                return ResourceManager.GetString("RacesMenuHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Racial Skill Modifiers.
        /// </summary>
        public static string RacialSkillModifiersLabel {
            get {
                return ResourceManager.GetString("RacialSkillModifiersLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ranged Attacks.
        /// </summary>
        public static string RangedLabel {
            get {
                return ResourceManager.GetString("RangedLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Range.
        /// </summary>
        public static string RangeLabel {
            get {
                return ResourceManager.GetString("RangeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reach.
        /// </summary>
        public static string ReachLabel {
            get {
                return ResourceManager.GetString("ReachLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reflex.
        /// </summary>
        public static string ReflexLabel {
            get {
                return ResourceManager.GetString("ReflexLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Related Spell.
        /// </summary>
        public static string RelatedEffectItemLabel {
            get {
                return ResourceManager.GetString("RelatedEffectItemLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remaining Rounds.
        /// </summary>
        public static string RemainingRoundsLabel {
            get {
                return ResourceManager.GetString("RemainingRoundsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Attribute.
        /// </summary>
        public static string RemoveAttributeHeader {
            get {
                return ResourceManager.GetString("RemoveAttributeHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string RemoveButton {
            get {
                return ResourceManager.GetString("RemoveButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string RemoveButtonToolTip {
            get {
                return ResourceManager.GetString("RemoveButtonToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Condition.
        /// </summary>
        public static string RemoveConditionMenuHeader {
            get {
                return ResourceManager.GetString("RemoveConditionMenuHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Effect.
        /// </summary>
        public static string RemoveEffectMenuHeader {
            get {
                return ResourceManager.GetString("RemoveEffectMenuHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are about to remove the source {0} and everything that comes from that source.  Are you sure you want to do this?.
        /// </summary>
        public static string RemoveSourceWarning {
            get {
                return ResourceManager.GetString("RemoveSourceWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove from this effect.
        /// </summary>
        public static string RemoveTargetMenuHeader {
            get {
                return ResourceManager.GetString("RemoveTargetMenuHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required Statistics.
        /// </summary>
        public static string RequiredStatsHeader {
            get {
                return ResourceManager.GetString("RequiredStatsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requirements.
        /// </summary>
        public static string RequirementsLabel {
            get {
                return ResourceManager.GetString("RequirementsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requires All Types.
        /// </summary>
        public static string RequiresAllLabel {
            get {
                return ResourceManager.GetString("RequiresAllLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset Campaign.
        /// </summary>
        public static string ReseetCampaignID {
            get {
                return ResourceManager.GetString("ReseetCampaignID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        public static string ResetViewButton {
            get {
                return ResourceManager.GetString("ResetViewButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resistances.
        /// </summary>
        public static string ResistancesLabel {
            get {
                return ResourceManager.GetString("ResistancesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Above Average.
        /// </summary>
        public static string RollingStrategyAboveAverage {
            get {
                return ResourceManager.GetString("RollingStrategyAboveAverage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Below Average.
        /// </summary>
        public static string RollingStrategyBelowAverage {
            get {
                return ResourceManager.GetString("RollingStrategyBelowAverage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heroic.
        /// </summary>
        public static string RollingStrategyHeroic {
            get {
                return ResourceManager.GetString("RollingStrategyHeroic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rolling Strategy.
        /// </summary>
        public static string RollingStrategyLabel {
            get {
                return ResourceManager.GetString("RollingStrategyLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum.
        /// </summary>
        public static string RollingStrategyMaximum {
            get {
                return ResourceManager.GetString("RollingStrategyMaximum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum.
        /// </summary>
        public static string RollingStrategyMinimum {
            get {
                return ResourceManager.GetString("RollingStrategyMinimum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Standard.
        /// </summary>
        public static string RollingStrategyStandard {
            get {
                return ResourceManager.GetString("RollingStrategyStandard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roll.
        /// </summary>
        public static string RollLabel {
            get {
                return ResourceManager.GetString("RollLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Would you like to save your current campaign first before closing it?.
        /// </summary>
        public static string SaveCampaignFirstMessage {
            get {
                return ResourceManager.GetString("SaveCampaignFirstMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Campaign.
        /// </summary>
        public static string SaveCampaignMenuHeader {
            get {
                return ResourceManager.GetString("SaveCampaignMenuHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving Throw.
        /// </summary>
        public static string SavingThrowLabel {
            get {
                return ResourceManager.GetString("SavingThrowLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to School.
        /// </summary>
        public static string SchoolLabel {
            get {
                return ResourceManager.GetString("SchoolLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select All.
        /// </summary>
        public static string SelectAllButton {
            get {
                return ResourceManager.GetString("SelectAllButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select One.
        /// </summary>
        public static string SelectItemWindowText {
            get {
                return ResourceManager.GetString("SelectItemWindowText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select One.
        /// </summary>
        public static string SelectItemWindowTitle {
            get {
                return ResourceManager.GetString("SelectItemWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Senses.
        /// </summary>
        public static string SensesLabel {
            get {
                return ResourceManager.GetString("SensesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string SettingsMenuHeader {
            get {
                return ResourceManager.GetString("SettingsMenuHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shapeable.
        /// </summary>
        public static string ShapeableLabel {
            get {
                return ResourceManager.GetString("ShapeableLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Short Description.
        /// </summary>
        public static string ShortDescriptionLabel {
            get {
                return ResourceManager.GetString("ShortDescriptionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size.
        /// </summary>
        public static string SizeLabel {
            get {
                return ResourceManager.GetString("SizeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skills.
        /// </summary>
        public static string SkillsLabel {
            get {
                return ResourceManager.GetString("SkillsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slot.
        /// </summary>
        public static string SlotLabel {
            get {
                return ResourceManager.GetString("SlotLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Small.
        /// </summary>
        public static string SmallSize {
            get {
                return ResourceManager.GetString("SmallSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort By.
        /// </summary>
        public static string SortByLabel {
            get {
                return ResourceManager.GetString("SortByLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source Attribute.
        /// </summary>
        public static string SourceAttributeLabel {
            get {
                return ResourceManager.GetString("SourceAttributeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source.
        /// </summary>
        public static string SourceButton {
            get {
                return ResourceManager.GetString("SourceButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source.
        /// </summary>
        public static string SourceLabel {
            get {
                return ResourceManager.GetString("SourceLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Special Abilities.
        /// </summary>
        public static string SpecialAbilitiesLabel {
            get {
                return ResourceManager.GetString("SpecialAbilitiesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Special Attacks.
        /// </summary>
        public static string SpecialAttacksLabel {
            get {
                return ResourceManager.GetString("SpecialAttacksLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Special Qualities.
        /// </summary>
        public static string SpecialQualitiesLabel {
            get {
                return ResourceManager.GetString("SpecialQualitiesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speed.
        /// </summary>
        public static string SpeedLabel {
            get {
                return ResourceManager.GetString("SpeedLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spell Like Abilities.
        /// </summary>
        public static string SpellLikeAbilitiesLabel {
            get {
                return ResourceManager.GetString("SpellLikeAbilitiesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spell Resistance.
        /// </summary>
        public static string SpellResistanceLabel {
            get {
                return ResourceManager.GetString("SpellResistanceLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spells.
        /// </summary>
        public static string SpellsCategory {
            get {
                return ResourceManager.GetString("SpellsCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spells.
        /// </summary>
        public static string SpellsMenuHeader {
            get {
                return ResourceManager.GetString("SpellsMenuHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stacking Rule.
        /// </summary>
        public static string StackingRuleLabel {
            get {
                return ResourceManager.GetString("StackingRuleLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Standard Damage.
        /// </summary>
        public static string StandardDamageLabel {
            get {
                return ResourceManager.GetString("StandardDamageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statistics.
        /// </summary>
        public static string StatisticsLabel {
            get {
                return ResourceManager.GetString("StatisticsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Strength.
        /// </summary>
        public static string StrengthLabel {
            get {
                return ResourceManager.GetString("StrengthLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subschool.
        /// </summary>
        public static string SubschoolLabel {
            get {
                return ResourceManager.GetString("SubschoolLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sub Types.
        /// </summary>
        public static string SubtypesLabel {
            get {
                return ResourceManager.GetString("SubtypesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tags.
        /// </summary>
        public static string TagsLabel {
            get {
                return ResourceManager.GetString("TagsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Targets.
        /// </summary>
        public static string TargetsLabel {
            get {
                return ResourceManager.GetString("TargetsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temporary Hit Points.
        /// </summary>
        public static string TemporaryHitPointsLabel {
            get {
                return ResourceManager.GetString("TemporaryHitPointsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tiny.
        /// </summary>
        public static string TinySize {
            get {
                return ResourceManager.GetString("TinySize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Touch Armor Class.
        /// </summary>
        public static string TouchArmorClassLabel {
            get {
                return ResourceManager.GetString("TouchArmorClassLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Touch Mode.
        /// </summary>
        public static string TouchModeMenuHeader {
            get {
                return ResourceManager.GetString("TouchModeMenuHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Treasure.
        /// </summary>
        public static string TreasureLabel {
            get {
                return ResourceManager.GetString("TreasureLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string TypeLabel {
            get {
                return ResourceManager.GetString("TypeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Types.
        /// </summary>
        public static string TypesLabel {
            get {
                return ResourceManager.GetString("TypesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unconscious At.
        /// </summary>
        public static string UnconsciousAtLabel {
            get {
                return ResourceManager.GetString("UnconsciousAtLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string UndoButtonLabel {
            get {
                return ResourceManager.GetString("UndoButtonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undoes back to the last time the current combatant changed (such as pressing the Next button).
        /// </summary>
        public static string UndoButtonToolTip {
            get {
                return ResourceManager.GetString("UndoButtonToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        public static string UnknownLabel {
            get {
                return ResourceManager.GetString("UnknownLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown Type.
        /// </summary>
        public static string UnknownType {
            get {
                return ResourceManager.GetString("UnknownType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Unnamed Source).
        /// </summary>
        public static string UnnamedSourceLabel {
            get {
                return ResourceManager.GetString("UnnamedSourceLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string UpButton {
            get {
                return ResourceManager.GetString("UpButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value.
        /// </summary>
        public static string ValueLabel {
            get {
                return ResourceManager.GetString("ValueLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ViewObjectButton {
            get {
                return ResourceManager.GetString("ViewObjectButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flavor Description.
        /// </summary>
        public static string VisualDescriptionLabel {
            get {
                return ResourceManager.GetString("VisualDescriptionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vulnierabilities.
        /// </summary>
        public static string VulnerabilitiesLabel {
            get {
                return ResourceManager.GetString("VulnerabilitiesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weight.
        /// </summary>
        public static string WeightLabel {
            get {
                return ResourceManager.GetString("WeightLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Willpower.
        /// </summary>
        public static string WIllpowerLabel {
            get {
                return ResourceManager.GetString("WIllpowerLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wisdom.
        /// </summary>
        public static string WisdomLabel {
            get {
                return ResourceManager.GetString("WisdomLabel", resourceCulture);
            }
        }
    }
}
