//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fiction.GameScreen.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Fiction.GameScreen.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Level.
        /// </summary>
        internal static string ClassLevelAttributeName {
            get {
                return ResourceManager.GetString("ClassLevelAttributeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class Level.
        /// </summary>
        internal static string ClassLevelAttributeType {
            get {
                return ResourceManager.GetString("ClassLevelAttributeType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class Level.
        /// </summary>
        internal static string ClassLevelModifierType {
            get {
                return ResourceManager.GetString("ClassLevelModifierType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  AND .
        /// </summary>
        internal static string DamageReductionAll {
            get {
                return ResourceManager.GetString("DamageReductionAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (dr |damage reduction )?(?&lt;amount&gt;\d+)/(?&lt;types&gt;.+).
        /// </summary>
        internal static string DamageReductionMask {
            get {
                return ResourceManager.GetString("DamageReductionMask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to and;or.
        /// </summary>
        internal static string DamageReductionTypeSplitter {
            get {
                return ResourceManager.GetString("DamageReductionTypeSplitter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Hit Dice.
        /// </summary>
        internal static string HitDiceByType {
            get {
                return ResourceManager.GetString("HitDiceByType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hit Dice.
        /// </summary>
        internal static string HitDieAttributeType {
            get {
                return ResourceManager.GetString("HitDieAttributeType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monster.
        /// </summary>
        internal static string MonsterSourceType {
            get {
                return ResourceManager.GetString("MonsterSourceType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Racial.
        /// </summary>
        internal static string RacialModifierType {
            get {
                return ResourceManager.GetString("RacialModifierType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spell.
        /// </summary>
        internal static string SpellSourceType {
            get {
                return ResourceManager.GetString("SpellSourceType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Hit Dice.
        /// </summary>
        internal static string TotalHitDiceAttributeName {
            get {
                return ResourceManager.GetString("TotalHitDiceAttributeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Level.
        /// </summary>
        internal static string TotalLevelAttributeName {
            get {
                return ResourceManager.GetString("TotalLevelAttributeName", resourceCulture);
            }
        }
    }
}
