//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fiction.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CommonResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CommonResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Fiction.Resources.CommonResources", typeof(CommonResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argument can not be the default value for its type.
        /// </summary>
        public static string ArgumentDefaultException {
            get {
                return ResourceManager.GetString("ArgumentDefaultException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum value for argument {0} not met..
        /// </summary>
        public static string ArgumentMinimumException {
            get {
                return ResourceManager.GetString("ArgumentMinimumException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argument must be non-negative.
        /// </summary>
        public static string ArgumentNegativeException {
            get {
                return ResourceManager.GetString("ArgumentNegativeException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argument must be non-negative.
        /// </summary>
        public static string ArgumentNegativeException1 {
            get {
                return ResourceManager.GetString("ArgumentNegativeException1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argument can not be of type {0}.
        /// </summary>
        public static string ArgumentTypeException {
            get {
                return ResourceManager.GetString("ArgumentTypeException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argument can not be null.
        /// </summary>
        public static string ExceptionArgumentNull {
            get {
                return ResourceManager.GetString("ExceptionArgumentNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to String must contain a value.
        /// </summary>
        public static string ExceptionStringEmpty {
            get {
                return ResourceManager.GetString("ExceptionStringEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to String must contain a value.
        /// </summary>
        public static string ExceptionStringEmpty1 {
            get {
                return ResourceManager.GetString("ExceptionStringEmpty1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item is not in the collection.
        /// </summary>
        public static string ItemNotInCollectionException {
            get {
                return ResourceManager.GetString("ItemNotInCollectionException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item is not in the collection.
        /// </summary>
        public static string ItemNotInCollectionException1 {
            get {
                return ResourceManager.GetString("ItemNotInCollectionException1", resourceCulture);
            }
        }
    }
}
