name: build-latest
on:
  workflow_dispatch:
    branches:
      - main
jobs:
  build-latest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_PUSH_ACCOUNT }}
          password: ${{ secrets.DOCKER_PUSH_PASSWORD }}
      - name:  Build and Push
        uses: docker/build-push-action@v3
        with:
          context: ./d20web
          push: true
          tags: starthoughts/d20web:latest
